import { transformResources } from "."
import { transformRpAcc } from "./user.transform"

export const transformOrderInv = (data:any) => {
	return {
		addInf1: data.AddInf1,
		addInf2: data.AddInf2,
		addInf3: data.AddInf3,
		addInf4: data.AddInf4,
		addInf5: data.AddInf5,
		addInf6: data.AddInf6,
		companyGuid: data.CGuid,
		companyId: data.CId,
		createdDate: data.CreatedDate,
		createdUId: data.CreatedUId,
		currencyCode: data.CurrencyCode,
		currencyId: data.CurrencyId,
		currencySymbol: data.CurrencySymbol,
		divGuid: data.DivGuid,
		divId: data.DivId,
		empId: data.EmpId,
		deleted: data.GCRecord,
		stausId: data.InvStatId,
		stausName: data.InvStatName,
		modifiedDate: data.ModifiedDate,
		modifiedUId: data.ModifiedUId,
		orderCreditDays: data.OInvCreditDays,
		orderCreditDesc: data.OInvCreditDesc,
		orderDate: data.OInvDate,
		orderDesc: data.OInvDesc,
		orderDiscountAmount: data.OInvDiscountAmount,
		orderExpenseAmount: data.OInvExpenseAmount,
		orderFTotal: data.OInvFTotal,
		orderFTotalInWrite: data.OInvFTotalInWrite,
		orderGuid: data.OInvGuid,
		orderId: data.OInvId,
		orderLatitude: data.OInvLatitude,
		orderLongitude: data.OInvLongitude,
		orderModifyCount: data.OInvModifyCount,
		orderPaymAmount: data.OInvPaymAmount,
		orderPrintCount: data.OInvPrintCount,
		orderRegNo: data.OInvRegNo,
		orderTaxAmount: data.OInvTaxAmount,
		orderTotal: data.OInvTotal,
		orderTypeId: data.OInvTypeId,
		paymentCode: data.PaymCode,
		paymentDesc: data.PaymDesc,
		paymentStatusId: data.PaymStatusId,
		paymentMethodId: data.PmId,
		paymentTypeId: data.PtId,
		rpAccGuid: data.RpAccGuid,
		rpAccId: data.RpAccId,
		rpAccRegNo: data.RpAccRegNo,
		syncDateTime: data.SyncDateTime,
		userGuid: data.UGuid,
		userId: data.UId,
		warehouseGuid: data.WhGuid,
		warehouseId: data.WhId,
		workPeriodId: data.WpId,
		rp_acc: transformRpAcc(data.Rp_acc)
	}
}

export const transformOrderInvLine = (data:any) => {
	return {
		addInf1: data.AddInf1,
		addInf2: data.AddInf2,
		addInf3: data.AddInf3,
		addInf4: data.AddInf4,
		addInf5: data.AddInf5,
		addInf6: data.AddInf6,
		createdDate: data.CreatedDate,
		createdUId: data.CreatedUId,
		currencyCode: data.CurrencyCode,
		currencyId: data.CurrencyId,
		currencySymbol: data.CurrencySymbol,
		excRateValue: data.ExcRateValue,
		deleted: data.GCRecord,
		LastVendorId: data.LastVendorId,
		modifiedDate: data.ModifiedDate,
		modifiedUId: data.ModifiedUId,
		orderId: data.OInvId,
		orderLineAmount: data.OInvLineAmount,
		orderLineDate: data.OInvLineDate,
		orderLineDesc: data.OInvLineDesc,
		orderLineDiscAmount: data.OInvLineDiscAmount,
		orderLineExpenseAmount: data.OInvLineExpenseAmount,
		orderLineFTotal: data.OInvLineFTotal,
		orderLineGuid: data.OInvLineGuid,
		orderLineId: data.OInvLineId,
		orderLinePrice: data.OInvLinePrice,
		orderLineRegNo: data.OInvLineRegNo,
		orderLineTaxAmount: data.OInvLineTaxAmount,
		orderLineTotal: data.OInvLineTotal,
		resGuid: data.ResGuid,
		resId: data.ResId,
		resRegNo: data.ResRegNo,
		syncDateTime: data.SyncDateTime,
		unitId: data.UnitId,
		resource: transformResources(data.Resources),
	}
}