import { transformRpAcc } from "sapredux/services/transform_data";

export const transformReview = (data:any) => (data.Rp_acc ? {
	addInf1: data.AddInf1,
	addInf2: data.AddInf2,
	addInf3: data.AddInf3,
	addInf4: data.AddInf4,
	addInf5: data.AddInf5,
	addInf6: data.AddInf6,
	companyId: data.CId,
	createdDate: data.CreatedDate,
	createdUId: data.CreatedUId,
	divId: data.DivId,
	empId: data.EmpId,
	deleted: data.GCRecord,
	modifiedDate: data.ModifiedDate,
	modifiedUId: data.ModifiedUId,
	resId: data.ResId,
	rpAccId: data.RpAccId,
	rp_acc: data.Rp_acc && transformRpAcc(data.Rp_acc),
	name: data.Rp_acc.RpAccName,
	username: data.Rp_acc.RpAccUName,
	avatar: data.Rp_acc.FilePathS,
	guid: data.RtGuid,
	id: data.RtId,
	ratingValue: data.RtRatingValue,
	remark: data.RtRemark,
	validated: data.RtValidated,
	syncDateTime: data.SyncDateTime,
	userId: data.UId,  
} : {})


export const toJsonReview = (data: any, allData: boolean = false) => ({
	AddInf1: data.addInf1 ?? null,
	AddInf2: data.addInf2 ?? null,
	AddInf3: data.addInf3 ?? null,
	AddInf4: data.addInf4 ?? null,
	AddInf5: data.addInf5 ?? null,
	AddInf6: data.addInf6 ?? null,
	CId: allData && (data.companyId ?? null),
	DivId: allData && (data.divId ?? null),
	EmpId: allData && (data.empId ?? null),
	ResId: data.resId ?? null,
	RpAccId: data.rpAccId ?? null,
	Rp_acc: data.rp_acc ?? null,
	RtGuid: data.guid ?? null,
	RtRatingValue: data.ratingValue ?? null,
	RtRemark: data.remark ?? null,
	RtValidated: allData && (data.validated ?? null),
	SyncDateTime: data.syncDateTime ?? null,
	UId: data.userId ?? null,
})
