export const transformRpAcc = (data:any) => ({
	addInf1: data.AddInf1,
	addInf2: data.AddInf2,
	addInf3: data.AddInf3,
	addInf4: data.AddInf4,
	addInf5: data.AddInf5,
	addInf6: data.AddInf6,
	companyId: data.CId,
	createdDate: data.CreatedDate,
	createdUId: data.CreatedUId,
	dbGuid: data.DbGuid,
	deviceQty: data.DeviceQty,
	divId: data.DivId,
	empId: data.EmpId,
	filePathM: data.FilePathM,
	filePathR: data.FilePathR,
	filePathS: data.FilePathS,
	image: data.FilePathS,
	deleted: data.GCRecord,
	genderId: data.GenderId,
	isMain: data.IsMain,
	modifiedDate: data.ModifiedDate,
	modifiedUId: data.ModifiedUId,
	natId: data.NatId,
	reprId: data.ReprId,
	priceGroupId: data.ResPriceGroupId,
	address: data.RpAccAddress,
	birthDate: data.RpAccBirthDate,
	email: data.RpAccEMail,
	name: data.RpAccName,
	firstName: data.RpAccFirstName,
	lastName: data.RpAccLastName,
	guid: data.RpAccGuid,
	homePhoneNumber: data.RpAccHomePhoneNumber,
	mobilePhoneNumber: data.RpAccMobilePhoneNumber,
	id: data.RpAccId,
	langSkills: data.RpAccLangSkills,
	lastActivityDate: data.RpAccLastActivityDate,
	lastActivityDevice: data.RpAccLastActivityDevice,
	latitude: data.RpAccLatitude,
	longitude: data.RpAccLongitude,
	passportIssuePlace: data.RpAccPassportIssuePlace,
	passportNo: data.RpAccPassportNo,
	patronomic: data.RpAccPatronomic,
	purchBalanceLimit: data.RpAccPurchBalanceLimit,
	regNo: data.RpAccRegNo,
	residency: data.RpAccResidency,
	saleBalanceLimit: data.RpAccSaleBalanceLimit,
	statusId: data.RpAccStatusId,
	typeId: data.RpAccTypeId,
	username: data.RpAccUName,
	viewCnt: data.RpAccViewCnt,
	visibleIndex: data.RpAccVisibleIndex,
	webAddress: data.RpAccWebAddress,
	workFaxNumber: data.RpAccWorkFaxNumber,
	workPhoneNumber: data.RpAccWorkPhoneNumber,
	zipCode: data.RpAccZipCode,
	workPeriodId: data.WpId,
	syncDateTime: data.SyncDateTime,
	unusedDeviceQty: data.UnusedDeviceQty,
})

export const toJsonRpAcc = (data: any, allData: boolean = false) => ({
	AddInf1: data.addInf1 ?? null,
	AddInf2: data.addInf2 ?? null,
	AddInf3: data.addInf3 ?? null,
	AddInf4: data.addInf4 ?? null,
	AddInf5: data.addInf5 ?? null,
	AddInf6: data.addInf6 ?? null,
	GenderId: data.genderId ?? null,
	NatId: data.natId ?? null,
	ReprId: data.reprId ?? null,
	RpAccAddress: data.address ?? null,
	RpAccBirthDate: data.birthDate ?? null,
	RpAccEMail: data.email ?? null,
	RpAccName: data.name ?? null,
	RpAccFirstName: data.firstName ?? null,
	RpAccLastName: data.lastName ?? null,
	RpAccHomePhoneNumber: data.homePhoneNumber ?? null,
	RpAccMobilePhoneNumber: data.mobilePhoneNumber ?? null,
	RpAccId: data.id ?? null,
	RpAccPassportNo: data.passportNo ?? null,
	RpAccPatronomic: data.patronomic ?? null,
	RpAccResidency: data.residency ?? null,
	RpAccUName: data.username ?? null,
	RpAccWebAddress: data.webAddress ?? null,
	RpAccWorkFaxNumber: data.workFaxNumber ?? null,
	RpAccWorkPhoneNumber: data.workPhoneNumber ?? null,
	RpAccZipCode: data.zipCode ?? null,
	RpAccTypeId: allData && (data.typeId ?? null),
	RpAccUPass: allData && (data.password ?? null),
})

export const transformUser = (data:any) => ({
	addInf1: data.AddInf1,
	addInf2: data.AddInf2,
	addInf3: data.AddInf3,
	addInf4: data.AddInf4,
	addInf5: data.AddInf5,
	addInf6: data.AddInf6,
	companyId: data.CId,
	createdDate: data.CreatedDate,
	createdUId: data.CreatedUId,
	divId: data.DivId,
	empId: data.EmpId,
	deleted: data.GCRecord,
	modifiedDate: data.ModifiedDate,
	modifiedUId: data.ModifiedUId,
	resPriceGroupId: data.ResPriceGroupId,
	rpAccId: data.RpAccId,
	syncDateTime: data.SyncDateTime,
	email: data.UEmail,
	fullname: data.UFullName,
	guid: data.UGuid,
	id: data.UId,
	lastActivityDate: data.ULastActivityDate,
	lastActivityDevice: data.ULastActivityDevice,
	name: data.UName,
	regNo: data.URegNo,
	shortName: data.UShortName,
	typeId: data.UTypeId,
})

export const transFormRpAccStatus = (data:any) => ({
	createdDate: data.CreatedDate,
	createdUId: data.CreatedUId,
	deleted: data.GCRecord,
	modifiedDate: data.ModifiedDate,
	modifiedUId: data.ModifiedUId,
	description: data.RpAccStatusDesc,
	guid: data.RpAccStatusGuid,
	id: data.RpAccStatusId,
	name: data.RpAccStatusName,
	syncDateTime: data.SyncDateTime,
})

export const transformRpAccType = (data:any) => ({
	createdDate: data.CreatedDate,
	createdUId: data.CreatedUId,
	deleted: data.GCRecord,
	modifiedDate: data.ModifiedDate,
	modifiedUId: data.ModifiedUId,
	description: data.RpAccTypeDesc,
	guid: data.RpAccTypeGuid,
	id: data.RpAccTypeId,
	name: data.RpAccTypeName,
	syncDateTime: data.SyncDateTime,
})
