export const rp_acc_basic_login_credentials = {
	username: 'mecreate',
	password: '111',
}

export const rp_acc_basic_login_failure = {
	message: 'Login failure, check credentials.',
	status: 0,
}

export const rp_acc_basic_login_success = {
	exp: '2021-09-29 09:29:10',
	rp_acc: {
		AddInf1: null,
		AddInf2: null,
		AddInf3: null,
		AddInf4: null,
		AddInf5: null,
		AddInf6: null,
		AddInf7: null,
		AddInf8: null,
		AddInf9: null,
		AddInf10: null,
		CId: 1,
		CreatedDate: '2021-09-16 13:29:13',
		CreatedUId: null,
		DbGuid: null,
		DeviceQty: null,
		DivId: 1,
		EmpId: null,
		FilePathM: '',
		FilePathR: '',
		FilePathS: '',
		GCRecord: null,
		GenderId: null,
		Images: [],
		IsMain: null,
		ModifiedDate: '2021-09-16 13:29:13',
		ModifiedUId: null,
		NatId: null,
		ReprId: null,
		ResPriceGroupId: null,
		RpAccAddress: '10 yyl abadanchylyk',
		RpAccBirthDate: null,
		RpAccEMail: 'test@mail.ru',
		RpAccFirstName: null,
		RpAccGuid: '440b08ff-d418-4fbd-8030-e5589d33426f',
		RpAccHomePhoneNumber: null,
		RpAccId: 45,
		RpAccLangSkills: null,
		RpAccLastActivityDate: '2021-09-16 13:30:15',
		RpAccLastActivityDevice:
			'Browser: chrome, Platform: linux, Details: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36',
		RpAccLastName: null,
		RpAccLatitude: 0.0,
		RpAccLongitude: 0.0,
		RpAccMobilePhoneNumber: '',
		RpAccName: 'Muhammetberdi',
		RpAccPassportIssuePlace: null,
		RpAccPassportNo: null,
		RpAccPatronomic: null,
		RpAccPurchBalanceLimit: 0.0,
		RpAccRegNo: 'ARAK4',
		RpAccResidency: null,
		RpAccSaleBalanceLimit: 0.0,
		RpAccStatusId: 1,
		RpAccTypeId: 2,
		RpAccUName: 'mecreate',
		RpAccViewCnt: null,
		RpAccVisibleIndex: null,
		RpAccWebAddress: null,
		RpAccWorkFaxNumber: null,
		RpAccWorkPhoneNumber: null,
		RpAccZipCode: null,
		Rp_acc_status: {
			CreatedDate: null,
			CreatedUId: 0,
			GCRecord: null,
			ModifiedDate: null,
			ModifiedUId: 0,
			RpAccStatusDesc: '',
			RpAccStatusGuid: null,
			RpAccStatusId: 1,
			RpAccStatusName: 'Işlewde',
			SyncDateTime: null,
		},
		Rp_acc_type: {
			CreatedDate: null,
			CreatedUId: 0,
			GCRecord: null,
			ModifiedDate: null,
			ModifiedUId: 0,
			RpAccTypeDesc: '',
			RpAccTypeGuid: null,
			RpAccTypeId: 2,
			RpAccTypeName: 'Alyjy',
			SyncDateTime: null,
		},
		SyncDateTime: '2021-09-16 13:29:13',
		UnusedDeviceQty: null,
		User: {
			AddInf1: null,
			AddInf2: null,
			AddInf3: null,
			AddInf4: null,
			AddInf5: null,
			AddInf6: null,
			AddInf7: null,
			AddInf8: null,
			AddInf9: null,
			AddInf10: null,
			CId: 1,
			CreatedDate: '2020-10-27 18:53:03',
			CreatedUId: null,
			DivId: 1,
			EmpId: null,
			GCRecord: null,
			ModifiedDate: '2020-11-07 23:21:46',
			ModifiedUId: null,
			ResPriceGroupId: null,
			RpAccId: 36,
			SyncDateTime: '2020-10-27 18:53:03',
			UEmail: 'muhammedjepbarov@gmail.com',
			UFullName: 'Mike Bionic',
			UGuid: null,
			UId: 3,
			ULastActivityDate: '2021-01-13 07:08:31',
			ULastActivityDevice: '',
			UName: 'administrator',
			URegNo: null,
			UShortName: 'AR',
			UTypeId: 1,
		},
		WpId: null,
	},
	token: 'somesecrethasheddata',
}
