export const all_brands = {
    "data": [
      {
        "AddInf1": null,
        "AddInf2": null,
        "AddInf3": null,
        "AddInf4": null,
        "AddInf5": null,
        "AddInf6": null,
        "BrandDesc": "A newly progressing company",
        "BrandGuid": null,
        "BrandId": 1,
        "BrandLink1": "www.sapchozgut.com",
        "BrandLink2": "",
        "BrandLink3": "",
        "BrandLink4": "",
        "BrandLink5": "",
        "BrandName": "Sap chozgut",
        "BrandVisibleIndex": 0,
        "CreatedDate": "2020-11-03 19:04:46",
        "CreatedUId": null,
        "GCRecord": null,
        "FilePath": "/ls/api/get-image/image/M/088d9d96b330d7bcd6b605b8be5b.png",
        "IsMain": true,
        "ModifiedDate": "2021-02-05 19:10:16",
        "ModifiedUId": null,
        "SyncDateTime": "2020-11-03 19:04:46"
      },
      {
        "AddInf1": null,
        "AddInf2": null,
        "AddInf3": null,
        "AddInf4": null,
        "AddInf5": null,
        "AddInf6": null,
        "BrandDesc": "apple company focuses on apple devices",
        "BrandGuid": null,
        "BrandId": 2,
        "BrandLink1": "www.apple.com",
        "BrandLink2": "+99364555934",
        "BrandLink3": "",
        "BrandLink4": "",
        "BrandLink5": "",
        "BrandName": "Apple",
        "BrandVisibleIndex": 0,
        "CreatedDate": "2020-12-24 13:39:37",
        "CreatedUId": null,
        "GCRecord": null,
        "FilePath": "/ls/api/get-image/image/M/6b2a38fcea759333ef56c99ed0bf.png",
        "IsMain": true,
        "ModifiedDate": "2021-02-05 19:10:16",
        "ModifiedUId": null,
        "SyncDateTime": "2020-12-24 13:39:37"
      },
      {
        "AddInf1": null,
        "AddInf2": null,
        "AddInf3": null,
        "AddInf4": null,
        "AddInf5": null,
        "AddInf6": null,
        "BrandDesc": "qwwd",
        "BrandGuid": null,
        "BrandId": 3,
        "BrandLink1": "www.rowshenshoes.tm",
        "BrandLink2": "",
        "BrandLink3": "",
        "BrandLink4": "",
        "BrandLink5": "",
        "BrandName": "dalhua",
        "BrandVisibleIndex": 0,
        "CreatedDate": "2021-02-05 15:13:07",
        "CreatedUId": null,
        "GCRecord": null,
        "FilePath": "/ls/api/get-image/image/M/cb6d86d706627af7231e29db04f0.svg",
        "IsMain": true,
        "ModifiedDate": "2021-02-06 10:03:15",
        "ModifiedUId": null,
        "SyncDateTime": "2021-02-05 15:13:07"
      }
    ],
    "message": "Brands",
    "status": 1,
    "total": 3
  }