export const all_categories = {
  "data": [
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": false,
      "ModifiedDate": "2021-01-21 23:35:54",
      "ModifiedUId": null,
      "ResCatDesc": "various high cquality sound system available",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/earbud_headphones.svg",
      "ResCatIconName": "earbud_headphones.svg",
      "ResCatId": 2,
      "ResCatName": "Nau\u015fniklar",
      "ResCatVisibleIndex": 0,
      "ResOwnerCatId": 12,
      "SyncDateTime": "2020-10-27 17:39:11"
    },
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": false,
      "ModifiedDate": "2021-06-25 13:59:49",
      "ModifiedUId": null,
      "ResCatDesc": "High speed full power latest laptops",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/laptop.svg",
      "ResCatIconName": "laptop.svg",
      "ResCatId": 5,
      "ResCatName": "Noutbuklar",
      "ResCatVisibleIndex": 0,
      "ResOwnerCatId": 10,
      "SyncDateTime": "2020-10-27 17:39:11"
    },
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": false,
      "ModifiedDate": "2021-10-03 16:41:15",
      "ModifiedUId": null,
      "ResCatDesc": "Pure coffe from arabica is easily cooked",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/electric_teapot.svg",
      "ResCatIconName": "electric_teapot.svg",
      "ResCatId": 8,
      "ResCatName": "Kofe bi\u015firijiler",
      "ResCatVisibleIndex": 0,
      "ResOwnerCatId": 0,
      "SyncDateTime": "2020-10-27 17:39:11"
    },
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": false,
      "ModifiedDate": "2021-02-04 17:52:20",
      "ModifiedUId": null,
      "ResCatDesc": "High resolution images taken by cameras are available in picures menu",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/bullet_camera.svg",
      "ResCatIconName": "bullet_camera.svg",
      "ResCatId": 6,
      "ResCatName": "Kameralar",
      "ResCatVisibleIndex": 0,
      "ResOwnerCatId": 1,
      "SyncDateTime": "2020-10-27 17:39:11"
    },
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": false,
      "ModifiedDate": "2021-02-04 17:52:20",
      "ModifiedUId": null,
      "ResCatDesc": "smartwatches available from now! hurry up",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/smart_watch.svg",
      "ResCatIconName": "smart_watch.svg",
      "ResCatId": 3,
      "ResCatName": "Sagatlar",
      "ResCatVisibleIndex": 0,
      "ResOwnerCatId": 12,
      "SyncDateTime": "2020-10-27 17:39:11"
    },
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": false,
      "ModifiedDate": "2021-03-08 23:17:41",
      "ModifiedUId": null,
      "ResCatDesc": "Meat freezes insanely fast",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/video_card.svg",
      "ResCatIconName": "video_card.svg",
      "ResCatId": 7,
      "ResCatName": "Sowadyjylar",
      "ResCatVisibleIndex": 0,
      "ResOwnerCatId": 0,
      "SyncDateTime": "2020-10-27 17:39:11"
    },
    {
      "CreatedDate": "2020-10-27 17:39:11",
      "CreatedUId": null,
      "GCRecord": null,
      "IsMain": true,
      "ModifiedDate": "2021-03-10 17:40:26",
      "ModifiedUId": null,
      "ResCatDesc": "latest models of smartphones with builtin AI",
      "ResCatGuid": null,
      "ResCatIconData": null,
      "ResCatIconFilePath": "/ls/api/get-icon/Electronics/smartphone_tablet.svg",
      "ResCatIconName": "smartphone_tablet.svg",
      "ResCatId": 1,
      "ResCatName": "Smartfonlar",
      "ResCatVisibleIndex": 2,
      "ResOwnerCatId": 0,
      "SyncDateTime": "2020-10-27 17:39:11"
    }
  ],
  "message": "All categories",
  "status": 1,
  "total": 7
}