export const company_info = {
	data: {
		AccInfId: 0,
		AddInf1: '8:00 - 18:00 | yone obed gelman',
		AddInf2: null,
		AddInf3: null,
		AddInf4: null,
		AddInf5: null,
		AddInf6: null,
		CAddress: 'Mir 7/4 18',
		CAddressLegal: null,
		CDesc:
			'Bizde oran ondebaryjy we hemme meselani chozyan haryt bardyr.. beyleki govno yerlere barman gowsy bizen alyn.. bizden alanyn ogly bolsyn, yone girip chykanyn gyzy bolsyn. sowulyp gechsen artygyn sagdyn bolsun, bizde 100 Manat sowda eden biz 1.5 baklashka Duye Caly sowgat!!',
		CEmail: 'muhammedjepbarov@gmail.com',
		CFullName: 'Lomay we bolekleyin aluw we satuw',
		CGuid: '7c05dec5-da68-47ce-bfd0-ac1591e9d3f4',
		CId: 1,
		CLatitude: 0.0,
		CLongitude: 0.0,
		CName: 'Lomay Sowda',
		CPostalCode: '4456',
		CreatedDate: '2020-10-27 17:35:03',
		CreatedUId: 6,
		GCRecord: null,
		ModifiedDate: '2021-08-25 16:15:32',
		ModifiedUId: 6,
		Phone1: '+9936342342',
		Phone2: '+9936343222',
		Phone3: null,
		Phone4: null,
		SyncDateTime: null,
		WebAddress: 'https://planyer.saphasap.com',
	},
	message: 'Company information',
	status: 1,
	total: 1,
}
