export const payment_methods = {
  "data": [
    {
      "AddInf1": null, 
      "AddInf2": null, 
      "AddInf3": null, 
      "AddInf4": null, 
      "AddInf5": null, 
      "AddInf6": null, 
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PmDesc": "Harydy alany\u0148yzda nagt pulda hasapla\u015fmak", 
      "PmGuid": null, 
      "PmId": 1, 
      "PmName": "Nagt", 
      "PmVisibleIndex": 1, 
      "SyncDateTime": null
    }, 
    {
      "AddInf1": null, 
      "AddInf2": null, 
      "AddInf3": null, 
      "AddInf4": null, 
      "AddInf5": null, 
      "AddInf6": null, 
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PmDesc": "T\u00f6leg karty\u0148yzdan online usulda hasapla\u015fmak", 
      "PmGuid": null, 
      "PmId": 2, 
      "PmName": "Online", 
      "PmVisibleIndex": 2, 
      "SyncDateTime": null
    }, 
    {
      "AddInf1": null, 
      "AddInf2": null, 
      "AddInf3": null, 
      "AddInf4": null, 
      "AddInf5": null, 
      "AddInf6": null, 
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PmDesc": "Harydy alany\u0148yzda kart bilen terminaldan hasapla\u015fmak", 
      "PmGuid": null, 
      "PmId": 3, 
      "PmName": "Terminal", 
      "PmVisibleIndex": 3, 
      "SyncDateTime": null
    }, 
    {
      "AddInf1": null, 
      "AddInf2": null, 
      "AddInf3": null, 
      "AddInf4": null, 
      "AddInf5": null, 
      "AddInf6": null, 
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PmDesc": "Bank hasapla\u015fyk hasaby\u0148yzdan t\u00f6leg ge\u00e7mek", 
      "PmGuid": null, 
      "PmId": 4, 
      "PmName": "Bank hasapdan t\u00f6leg", 
      "PmVisibleIndex": 4, 
      "SyncDateTime": null
    }, 
    {
      "AddInf1": null, 
      "AddInf2": null, 
      "AddInf3": null, 
      "AddInf4": null, 
      "AddInf5": null, 
      "AddInf6": null, 
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PmDesc": "Sowgat kart usuly bilen online hasapla\u015fmak", 
      "PmGuid": null, 
      "PmId": 5, 
      "PmName": "Sowgat karty", 
      "PmVisibleIndex": 5, 
      "SyncDateTime": null
    }
  ], 
  "message": "Payment methods", 
  "status": 1, 
  "total": 5
}

export const payment_types = {
  "data": [
    {
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PtDesc": "Harydy alany\u0148yzda hasapla\u015fmak", 
      "PtGuid": null, 
      "PtId": 1, 
      "PtName": "Nagt", 
      "PtVisibleIndex": 1, 
      "SyncDateTime": null
    }, 
    {
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PtDesc": "Sa\u00fdlanan m\u00f6hlete \u00e7enli gara\u015faryna almaklyk. 30%-ni nagt t\u00f6lemek bilen", 
      "PtGuid": null, 
      "PtId": 2, 
      "PtName": "Kredit", 
      "PtVisibleIndex": 2, 
      "SyncDateTime": null
    }, 
    {
      "CreatedDate": null, 
      "CreatedUId": 0, 
      "GCRecord": null, 
      "ModifiedDate": null, 
      "ModifiedUId": 0, 
      "PtDesc": "Harytlary\u0148 t\u00f6legini harydy satany\u0148yzdan so\u0148 hasapla\u015fmak", 
      "PtGuid": null, 
      "PtId": 3, 
      "PtName": "Sataryna", 
      "PtVisibleIndex": 3, 
      "SyncDateTime": null
    }
  ], 
  "message": "Payment types", 
  "status": 1, 
  "total": 3
}