export const authConstants = {
	REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

	LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

	RESET_PASSWORD_REQUEST: 'AUTH_RESET_PASSWORD_REQUEST',
	RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS',
	RESET_PASSWORD_FAILURE: 'AUTH_RESET_PASSWORD_FAILURE',

	LOGOUT: 'AUTH_LOGOUT',
	PROFILE_UPDATE: 'AUTH_PROFILE_UPDATE',
};