export const resourceCollectionConstants = {
	FETCH_START: 'RESOURCE_COLLECTION_FETCH_START',
	FETCH_SUCCESS: 'RESOURCE_COLLECTION_FETCH_SUCCESS',
	FETCH_FAILURE: 'RESOURCE_COLLECTION_FETCH_FAILURE',
}
