export const resourceConstants = {
	FETCH_START: 'RESOURCE_FETCH_START',
	FETCH_SUCCESS: 'RESOURCE_FETCH_SUCCESS',
	FETCH_FAILURE: 'RESOURCE_FETCH_FAILURE',

	LOAD_MORE_START: 'RESOURCE_LOAD_MORE_START',
	LOAD_MORE_SUCCESS: 'RESOURCE_LOAD_MORE_SUCCESS',
	LOAD_MORE_FAILURE: 'RESOURCE_LOAD_MORE_FAILURE',

	FETCH_BY_ID_START: 'RESOURCE_FETCH_BY_ID_START',
	FETCH_BY_ID_SUCCESS: 'RESOURCE_FETCH_BY_ID_SUCCESS',
	FETCH_BY_ID_FAILURE: 'RESOURCE_FETCH_BY_ID_FAILURE',

	ADDED_TO_CART: 'RESOURCE_ADDED_TO_CART',
	REMOVED_FROM_CART: 'RESOURCE_REMOVED_FROM_CART',
	ALL_REMOVED_FROM_CART: 'RESOURCE_ALL_REMOVED_FROM_CART',

	FEATURED_FETCH_START: 'RESOURCE_FEATURED_FETCH_START',
	FEATURED_FETCH_SUCCESS: 'RESOURCE_FEATURED_FETCH_SUCCESS',
	FEATURED_FETCH_FAILURE: 'RESOURCE_FEATURED_FETCH_FAILURE',

	DISCOUNT_FETCH_START: 'RESOURCE_DISCOUNT_FETCH_START',
	DISCOUNT_FETCH_SUCCESS: 'RESOURCE_DISCOUNT_FETCH_SUCCESS',
	DISCOUNT_FETCH_FAILURE: 'RESOURCE_DISCOUNT_FETCH_FAILURE',

	WISHLIST_FETCH_START: 'WISHLIST_FETCH_START',
	WISHLIST_FETCH_SUCCESS: 'WISHLIST_FETCH_SUCCESS',
	WISHLIST_FETCH_FAILURE: 'WISHLIST_FETCH_FAILURE',

	LATEST_FETCH_START: 'RESOURCE_LATEST_FETCH_START',
	LATEST_FETCH_SUCCESS: 'RESOURCE_LATEST_FETCH_SUCCESS',
	LATEST_FETCH_FAILURE: 'RESOURCE_LATEST_FETCH_FAILURE',
}
