export const resourceConstants = {
	FETCH_START: 'RESOURCE_FETCH_START',
	FETCH_SUCCESS: 'RESOURCE_FETCH_SUCCESS',
	FETCH_FAILURE: 'RESOURCE_FETCH_FAILURE',
	ADDED_TO_CART: 'RESOURCE_ADDED_TO_CART',
	REMOVED_FROM_CART: 'RESOURCE_REMOVED_FROM_CART',
	ALL_REMOVED_FROM_CART: 'RESOURCE_ALL_REMOVED_FROM_CART',
};